### ISSUE TITLE
Some Errors?

### ISSUE THREAD

**Issue by lovechang1986** [ASRCsoft/hysplit_xcite#7]
As I download the zipfile and opened in chrome after decompressed. Some errors occurs like below:
`index.html:1 Failed to load http://pireds.asrc.cestm.albany.edu:5000/times: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
index.html:1 Failed to load http://pireds.asrc.cestm.albany.edu:5000/sites: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

But while load the url in chrome without any errors, it get some infos like longtitudes and latitudes.
What happened ?
 
Another Question: Is any plan to show the hysplit concentration result using javascript on google or openstreet map?

**Comment by wmay** [comment]
Hi lovechang,
Though this is a public repository, we aren't currently supporting this tool for anyone outside of the ASRC/NYS Mesonet.

I'm hoping to refactor this code to create a standalone HYSPLIT javascript package, which you could use to display the concentrations over any maps supported by leaflet. But it'll be a few months at least before that's released.
